// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BondUIClient is the client API for BondUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BondUIClient interface {
	// ListEngineSpecs returns a list of Bond Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (BondUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type bondUIClient struct {
	cc grpc.ClientConnInterface
}

func NewBondUIClient(cc grpc.ClientConnInterface) BondUIClient {
	return &bondUIClient{cc}
}

func (c *bondUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (BondUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &BondUI_ServiceDesc.Streams[0], "/v1.BondUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &bondUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BondUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type bondUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *bondUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bondUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.BondUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BondUIServer is the server API for BondUI service.
// All implementations must embed UnimplementedBondUIServer
// for forward compatibility
type BondUIServer interface {
	// ListEngineSpecs returns a list of Bond Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, BondUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedBondUIServer()
}

// UnimplementedBondUIServer must be embedded to have forward compatible implementations.
type UnimplementedBondUIServer struct {
}

func (UnimplementedBondUIServer) ListEngineSpecs(*ListEngineSpecsRequest, BondUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedBondUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedBondUIServer) mustEmbedUnimplementedBondUIServer() {}

// UnsafeBondUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BondUIServer will
// result in compilation errors.
type UnsafeBondUIServer interface {
	mustEmbedUnimplementedBondUIServer()
}

func RegisterBondUIServer(s grpc.ServiceRegistrar, srv BondUIServer) {
	s.RegisterService(&BondUI_ServiceDesc, srv)
}

func _BondUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BondUIServer).ListEngineSpecs(m, &bondUIListEngineSpecsServer{stream})
}

type BondUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type bondUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *bondUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BondUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BondUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BondUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BondUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BondUI_ServiceDesc is the grpc.ServiceDesc for BondUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BondUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.BondUI",
	HandlerType: (*BondUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _BondUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _BondUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bond-ui.proto",
}
